name: Bundle OSDev Wiki UI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Build
      run: |
        yarn install
        gulp bundle
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: osdev-wiki-ui.zip
        path: build/ui-bundle.zip
